import { readFileSync } from "node:fs";
import { defineConfig } from "wxt";

const sourceManifest = JSON.parse(
  readFileSync(new URL("./manifest.json", import.meta.url), "utf8"),
);

export default defineConfig({
  imports: false,
  manifestVersion: 3,
  manifest: {
    name: "Unfluffify",
    version: sourceManifest.version,
    description:
      "Chrome extension to label what's non-meaningful text content to help AI find the meaningful text content.",
    action: {
      default_title: "Unfluffify",
    },
    permissions: [
      "storage",
      "sidePanel",
      "tabs",
      "scripting",
      "debugger",
      "alarms",
      "browsingData",
      "webNavigation",
      "activeTab",
      "offscreen",
    ],
    host_permissions: ["<all_urls>"],
    web_accessible_resources: [
      {
        resources: [
          "content-main.js",
          "content/constants.js",
          "content/core.js",
          "content/marking-rules.js",
          "content/shared-inclusion.js",
          "content/shared-selector-cache.js",
          "content/silent-highlight-rules.js",
          "content/submission-rules.js",
          "content/content-command-router.js",
          "content/content-main-service-registry.js",
          "content/ai-preview-close-handler.js",
          "content/ai-preview-compute-lock-handler.js",
          "content/ai-preview-expanded-mode-handler.js",
          "content/ai-preview-get-state-handler.js",
          "content/ai-preview-show-handler.js",
          "content/ai-preview-state-response.js",
          "content/ai-submission-xpaths-handler.js",
          "content/capture-page-snapshot-handler.js",
          "content/collect-page-data-handler.js",
          "content/config-updated-handler.js",
          "content/default-exclusions-handler.js",
          "content/describe-xpaths-handler.js",
          "content/explicit-marking-handler.js",
          "content/focus-handler.js",
          "content/force-refresh-handler.js",
          "content/invisible-xpaths-handler.js",
          "content/inspection-status.js",
          "content/page-draft-revert-handler.js",
          "content/page-draft-save-handler.js",
          "content/page-draft-status-handler.js",
          "content/page-save-reconciliation-clear-handler.js",
          "content/page-world-relay.js",
          "content/page-save-reconciliation-pending-handler.js",
          "content/page-toast.js",
          "content/render-mode-inspection-handlers.js",
          "content/render-mode-inspection-client.js",
          "content/property-lock-banner.js",
          "content/property-lock-banner-mode.js",
          "content/property-lock-port-client.js",
          "content/property-lock-state-machine.js",
          "content/runtime-message-handler.js",
          "content/visible-xpaths-handler.js",
          "common/config.js",
          "common/constants.js",
          "common/feature-flags.js",
          "common/lynx-checklist.js",
          "common/lynx-live-pages.js",
          "common/message-protocol.js",
          "common/page-world-protocol.js",
          "common/property-lock.js",
          "common/selector-set.js",
          "common/settings-store.js",
          "common/storage-core.js",
          "common/text.js",
          "common/utilities.js",
          "common/world-messaging-contract.js",
          "background/tab-session-store.js",
          "assets/materialdesignicons-webfont.woff2",
          "cursors/*.svg"
        ],
        matches: ["<all_urls>"]
      }
    ],
    icons: {
      "16": "icons/default/icon16.png",
      "32": "icons/default/icon32.png",
      "48": "icons/default/icon48.png",
      "128": "icons/default/icon128.png"
    },
  },
});
