export const REMOVABLE_ELEMENT_SELECTORS = [
  ":not(body):not(html).backdrop",
  ":not(body):not(html).overlay",
  ":not(body):not(html).wcc-overlay",
  ":not(body):not(html).modal-backdrop",
  ":not(body):not(html)[role='dialog' i]",
  ":not(body):not(html)[role='modal' i]",
  ":not(body):not(html)[role='popup' i]",
  ":not(body):not(html)[class*='modal' i]",
  ":not(body):not(html)[class*='popup' i]",
  ":not(body):not(html)[id*='cookie' i]",
  ":not(body):not(html)[class*='cookie' i]",
  ":not(body):not(html)[id*='consent' i]",
  ":not(body):not(html)[class*='consent' i]",
  ":not(body):not(html)[aria-label*='cookie' i]",
  ":not(body):not(html)[aria-label*='consent' i]",
  ":not(body):not(html)[aria-label*='modal' i]",
  ":not(body):not(html)[aria-label*='popup' i]",
  ":not(body):not(html)[aria-label*='dialog' i]",
  ":not(body):not(html)[aria-label*='newsletter' i]",
  ":not(body):not(html)[aria-label*='subscribe' i]"
];
