export const state = {
  enabled: false,
  baseUrl: "",
  config: null,
  overlay: null,
  layers: {},
  hoverBox: null,
  focusBox: null,
  focusElement: null,
  aiPopover: null,
  toast: null,
  toastHideTimer: 0,
  altPassThrough: false,
  lastPointer: null,
  markIdCounter: 1,
  markIds: new WeakMap(),
  markedElements: new Set(),
  renderRaf: 0,
  renderTimer: 0,
  scrollHideTimer: 0,
  isScrolling: false,
  snapshotTimer: 0,
  urlCheckTimer: 0,
  mutationObserver: null,
  savedPageEntry: null,
  savedPageUrl: "",
  initialized: false
};
