import type { Config, PageMarkingEntry } from "./config.ts";

export interface ExplicitToggleJob {
  target: Element;
  mode: "include" | "exclude";
  key: string;
  interactionNow: number;
}

export interface MarkingCollections {
  hardElements: Element[];
  explicitExcludeElements: Element[];
  explicitIncludeElements: Element[];
  hiddenExplicitIncludeElements: Element[];
  fetchedExplicitExcludeElements: Element[];
  fetchedExplicitIncludeElements: Element[];
  hiddenFetchedExplicitIncludeElements: Element[];
  sessionExplicitExcludeElements: Element[];
  sessionExplicitIncludeElements: Element[];
  hiddenSessionExplicitIncludeElements: Element[];
  aiAnimatedExplicitIncludeElements: Element[];
  hiddenAiAnimatedExplicitIncludeElements: Element[];
  aiContentElements: Element[];
  hiddenAiContentElements: Element[];
  selectorExcludedElements: Element[];
  defaultElements: Element[];
}

export interface ContentState {
  enabled: boolean;
  baseUrl: string;
  currentPageType: string;
  config: Config | null;
  overlay: HTMLDivElement | null;
  layers: Record<string, HTMLDivElement | null>;
  hoverBox: HTMLDivElement | null;
  focusBox: HTMLDivElement | null;
  focusElement: Element | null;
  aiPopover: HTMLElement | null;
  aiPopoverCollapsed: boolean;
  aiPopoverOnClose: (() => void) | null;
  aiPopoverOnCollapsedChange: ((collapsed: boolean) => void) | null;
  toast: HTMLElement | null;
  toastHideTimer: number;
  markingDisabledNotice: HTMLElement | null;
  pageInspectionNotice: HTMLElement | null;
  pageInspectionUiEnabled: boolean;
  inspectionBlocker: HTMLElement | null;
  popupBusyOverlay: HTMLElement | null;
  popupBusyNotice: HTMLElement | null;
  popupBusyBlocker: HTMLElement | null;
  popupBusyFailOpenTimer: number;
  popupBusyOperationId: string;
  popupBusyReleaseBy: number;
  altPassThrough: boolean;
  altHeld: boolean;
  shiftHeld: boolean;
  lastPointer: { x: number; y: number } | null;
  markIdCounter: number;
  markIds: WeakMap<object, number>;
  markedElements: Set<Element>;
  renderRaf: number;
  renderTimer: number;
  explicitFullRenderTimer: number;
  pendingRenderInvalidate: boolean;
  lastRenderAt: number;
  scrollHideTimer: number;
  isScrolling: boolean;
  snapshotTimer: number;
  draftPersistTimer: number;
  urlCheckTimer: number;
  mutationObserver: MutationObserver | null;
  savedPageEntry: PageMarkingEntry | null;
  savedPageUrl: string;
  cleanBaselineFingerprintByPageUrl: Map<string, string>;
  pageSaveReconciliation: Record<string, unknown> | null;
  pendingFreshBaselinePageUrl: string;
  consentSyncedPageUrl: string;
  consentRootElements: Set<Element>;
  initialized: boolean;
  layerBoxes: WeakMap<object, DOMRectReadOnly[]>;
  cachedCollections: MarkingCollections | null;
  cachedCollectionsKey: string;
  markingSettleTimers: number[];
  paintReachabilityFallbackCount: number;
  paintReachabilityFallbackLastLoggedAt: number;
  elementComputationCacheDepth: number;
  visibilityCache: WeakMap<object, boolean> | null;
  ancestorVisStateCache: WeakMap<object, boolean> | null;
  ancestorOverflowCache: WeakMap<object, boolean> | null;
  directTextCache: WeakMap<object, string> | null;
  normalizedTextCache: WeakMap<object, string> | null;
  toggleableDefaultCache: WeakMap<object, boolean> | null;
  immutableMatchCache: WeakMap<object, boolean> | null;
  immutableAncestorCache: WeakMap<object, boolean> | null;
  textualContainerCache: WeakMap<object, boolean> | null;
  textualDescendantCache: WeakMap<object, boolean> | null;
  textualImmutableDescendantCache: WeakMap<object, boolean> | null;
  hoverRaf: number;
  currentPageUrl: string;
  currentPageEntry: PageMarkingEntry | null;
  autoSeededPendingSavePageUrl: string;
  autoSeedSuppressedPageUrl: string;
  toggleAckTimer: number;
  toggleInFlightKey: string;
  toggleQueuedActionKey: string;
  toggleMutationQueue: ExplicitToggleJob[];
  toggleMutationHandle: number;
  toggleMutationHandleType: string;
  toggleReconcileGeneration: number;
  lastToggleActionKey: string;
  lastToggleActionAt: number;
  explicitOverlayRefreshScheduled: boolean;
  explicitOverlayRefreshHandle: number;
  explicitOverlayRefreshHandleType: string;
  explicitOverlayRefreshEntry: PageMarkingEntry | null;
  explicitOverlayRefreshContext: Record<string, unknown> | null;
  pageMotionPause: Record<string, unknown> | null;
  pageRevealWarmupId: number;
  lazyLoadSuppressRestorer: (() => void) | null;
  perfEnabled: boolean | null;
}
