import { DEVICE_SCALE_DEFAULTS } from "../common/constants.js";

export const DEVICE_SCALE_LIMITS = {
  min: 0.25,
  max: 1,
  step: 0.01
};

export const state = {
  currentView: "Marking",
  currentTab: null,
  currentBaseUrl: "",
  currentConfig: null,
  toastTimer: 0,
  refreshTimer: 0,
  lastTabId: null,
  baseUrlEditMode: false,
  stageBaseEditMode: false,
  endpointEditMode: false,
  configEndpointEditMode: false,
  aiRequestInFlight: null,
  aiSelectorsComputedSinceLastSubmit: false,
  aiSelectorsComputedBaseUrl: "",
  configMenuOpen: false,
  currentDeviceMode: "mobile",
  currentDeviceScale: DEVICE_SCALE_DEFAULTS.mobile,
  currentDeviceEmulationEnabled: false,
  deviceControlsDisabled: false,
  currentDraftEntry: null,
  currentSavedEntry: null,
  currentDraftDirty: false,
  currentDraftAvailable: false,
  currentDraftHasEntry: false,
  clearDomainCacheDisabled: false,
  unregisterCurrentTabDisabled: false,
  lastPopupPageUrl: "",
  lastPopupEnabled: null,
  silentHighlightShowMarkedPages: true,
  silentHighlightShowIncludedContent: true,
  silentHighlightShowExcludedContent: false,
  silentHighlightShowVisibleConsent: false,
  silentHighlightHideDuringScrollRedraw: true,
  lastAppliedSilentHighlightKey: "",
  lastAppliedSilentHighlightTabId: null,
  lastAppliedSilentHighlightPageUrl: "",
  configViewLocked: false,
  tokenValidationInFlight: false,
  lastTokenValidationAt: 0,
  tokenValidationTimer: 0,
  remoteConfigLoadKey: "",
  remoteConfigLoadResult: null,
  lastConfigLoadStatusText: "Not loaded yet",
  lastConfigSaveStatusText: "No save sent yet",
  mobileAutoAppliedTabIds: new Set(),
  sidebarScaleRefitScheduledTabIds: new Set(),
  siteIdLookupByBaseUrl: new Map()
};
