import { DEVICE_SCALE_DEFAULTS } from "../common/constants.js";
import { createInitialLynxChecklistState } from "../common/lynx-checklist.js";

const initialLynxChecklistState = createInitialLynxChecklistState();

export const state = {
  currentView: "Marking",
  currentTheme: "nordic",
  currentThemeMode: "system",
  currentTab: null,
  currentBaseUrl: "",
  currentSiteId: "",
  currentConfig: null,
  toastTimer: 0,
  refreshTimer: 0,
  observerRemoteConfigRefreshTimer: 0,
  lastTabId: null,
  stageBaseEditMode: false,
  endpointEditMode: false,
  configEndpointEditMode: false,
  renderModeEditMode: false,
  aiRequestInFlight: null,
  aiRunPhase: "",
  aiRunSessionId: "",
  aiRunSiteId: "",
  aiRunDeadlineAt: 0,
  aiRunRemainingMs: 0,
  aiRunResumeExpiresAt: 0,
  aiRunResumed: false,
  aiRunPollTimer: 0,
  aiRunCountdownTimer: 0,
  aiRunResumeCheckKey: "",
  aiRunResumeInFlight: false,
  aiSelectorsComputedSinceLastSubmit: false,
  aiSelectorsComputedBaseUrl: "",
  // Fingerprint of the page markings (exclude + include xpaths) captured at the
  // moment the last successful AI run completed for the current page. Used to
  // gate Run AI / Save / Preview: while this equals the live markings, the AI
  // output is up to date (Run AI disabled, Save/Preview enabled); any
  // mark/unmark change makes it differ (Run AI re-enabled, Save/Preview off).
  // null means no successful run for the current page since enabling marking.
  aiRunMarkingsFingerprint: null,
  configMenuOpen: false,
  basePageMenuOpen: false,
  currentTodoExpansionKey: "",
  todoExpansionStateByContext: new Map(),
  renderModeSummaryOpen: false,
  currentDeviceMode: "mobile",
  currentDeviceScale: DEVICE_SCALE_DEFAULTS.mobile,
  currentDeviceEmulationEnabled: false,
  deviceControlsDisabled: false,
  currentDraftEntry: null,
  currentSavedEntry: null,
  currentDraftDirty: false,
  currentDraftAvailable: false,
  currentPageSaveReconciliation: null,
  currentPageSaveReconciliationPending: false,
  currentPageTypeKey: "",
  currentPageTypeTitle: "",
  clearDomainCacheDisabled: false,
  unregisterCurrentTabDisabled: false,
  remoteSupportState: null,
  remoteSupportJoinCode: "",
  remoteSupportLastFrame: "",
  remoteSupportViewLocked: false,
  lastPopupPageUrl: "",
  lastPopupEnabled: null,
  lastPopupEnabledContext: null,
  configViewLocked: false,
  tokenValidationInFlight: false,
  lastTokenValidationAt: 0,
  tokenValidationTimer: 0,
  renderModeDetectionInFlight: false,
  renderModeDetectionKey: "",
  renderModeDetectionUnsure: false,
  renderModeDetectionAccuracy: Number.NaN,
  renderModeSuggestedKey: "",
  renderModeSuggestedValue: "undetermined",
  renderModeInspectionSnapshotKey: "",
  renderModeInspectionSnapshot: null,
  renderModeInspectionActive: false,
  renderModeUndeterminedNoticeKey: "",
  renderModeWarningDismissedKey: "",
  renderModeManualStepsVisible: false,
  renderModeDebuggerTabId: null,
  currentBaseUrlHasConfirmedRenderMode: false,
  remoteConfigLoadKey: "",
  remoteConfigLoadResult: null,
  remoteConfigConnectionIssue: false,
  remoteConfigConnectionRetryTimer: 0,
  lastConfigLoadStatusText: "Not loaded yet",
  lastConfigLoadStatusTone: "muted",
  lastConfigSaveStatusText: "No save sent yet",
  lastConfigSaveStatusTone: "muted",
  siteIdLookupByBaseUrl: new Map(),
  propertyPageTypes: [],
  propertyPageTypesDuplicateUrls: [],
  propertyPageTypesSiteId: null,
  propertyPageTypesStageBase: "",
  propertyPageTypesSignature: "",
  propertyPageTypesFetchedAt: 0,
  propertyPageTypesRefreshTimer: 0,
  propertyPageTypesRefreshKey: "",
  propertyPageTypesLastError: "",
  propertyPageTypesChangeNoticeVisible: false,
  propertyPageTypesInvalidAlertPending: false,
  propertyPageTypesChangeForceTodoOpen: false,
  traceModeEnabled: false,
  removedRemotePageKeys: new Set(),
  propertyLockSiteId: null,
  propertyLockState: null,
  propertyLockConnectionStatus: "inactive",
  propertyLockConnectionError: "",
  propertyLockIdentity: "",
  propertyLockName: "",
  propertyLockClientId: "",
  propertyLockSecondsRemaining: null,
  propertyLockSuggestionId: "",
  propertyLockSuggestionFromName: "",
  propertyLockSuggestionVisible: false,
  propertyLockSuggestionPending: false,
  propertyLockSuggestionRejected: false,
  propertyLockInactivityWarningVisible: false,
  propertyLockDisconnectCountdown: null,
  propertyLockTransferCountdown: null,
  propertyLockEditorBootstrapPending: false,
  lynxChecklistVisible: false,
  lynxChecklistAiAnswer: initialLynxChecklistState.aiAnswer,
  lynxChecklistPageTypes: initialLynxChecklistState.pageTypes,
  lynxChecklistAiQuestionDisabled: true,
  lynxChecklistAiQuestionHidden: true,
  lynxChecklistNoticeText: ""
};
